---@class OneDarkProOriginColor
---@field chalky string
---@field coral string
---@field dark string
---@field deepRed string
---@field error string
---@field fountainBlue string
---@field green string
---@field invalid string
---@field lightDark string
---@field lightWhite string
---@field malibu string
---@field purple string
---@field whiskey string

---@class OneDarkProOriginColors
---@field classic OneDarkProOriginColor
---@field vivid OneDarkProOriginColor
